sudo apt update
sudo apt upgrade
sudo apt install m4
sudo apt install gcc
sudo apt install g++
sudo apt install bridge-utils
sudo apt install curl
sudo apt install libssl-dev
sudo apt install python3
sudo apt install python3-dev
sudo apt install htop
sudo apt install screen
sudo apt install flex
sudo apt install automake
sudo apt install libtool
sudo apt install make
sudo apt install gcc
sudo apt install pkg-config
sudo apt install bison
sudo apt install python3-dev
sudo apt install python3-pip
sudo apt install virtualenv
sudo apt install ocaml
sudo apt install ocaml-native-compilers
sudo apt install camlp4-extra
sudo apt install git
sudo apt install curl
sudo apt install build-essential
sudo apt install m4
